baseURL = 'https://tylermorales.pro/'
languageCode = 'en-us'
title = 'Tylers New and Improved Website'

[outputs]
  home = ['HTML', 'JSON']

[outputFormats]
  [outputFormats.JSON]
    mediaType = 'application/json'
    baseName = 'index'
    isPlainText = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

disableKinds = ["taxonomy", "term"]

[imaging]
  quality = 75
  resampleFilter = 'lanczos'

[frontmatter]
  lastmod = ["lastmod", ":git", "date"]